services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    depends_on:
      - api
      - cache
      - db

  api:
    build: ./apic
    container_name: api
    ports:
      - "4000:3000"
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret123  
      - POSTGRES_DB=mydb
    depends_on:
      - cache
      - db

  cache:
    image: redis:latest
    container_name: cache
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=NewStrongPass456!
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
